### ISSUE TITLE
加入 webdav 和 https server

### ISSUE THREAD

**Issue by 1a57danc3** [getnas/getnas#14]
https://github.com/hacdias/webdav

https://github.com/mholt/caddy

**Comment by yuhr123** [comment]
是否可以说下你想象中，独立实现 webdav 协议的主要应用场景是怎样的？

PS：项目中 Nextcloud 自带 webdav 协议支持。

**Comment by 1a57danc3** [comment]
@yuhr123 我不是很喜歡 php 的相關產品，替代品還有 seafile 的 webdav extension https://manual.seafile.com/extension/webdav.html
