### ISSUE TITLE
为什么要使用RAID 1磁盘阵列

### ISSUE THREAD

**Issue by xiaoxinpro** [getnas/getnas#4]
感觉机械硬盘出问题的概率好低的，家中的台式机80G硬盘用了十几年也没有出现数据丢失的情况，而且将两个1T的硬盘合在一起感觉好浪费啊。

**Comment by yuhr123** [comment]
我这里考虑数据存储的是数据安全问题，作为以数据备份和共享为主要用途服务器，应该具备起码的数据冗余机制。相比之下，RAID 1 配置要更简单，管理也更方便。

如果不用 RAID 1 磁盘阵列，你是否有更好的数据安全方案或管理经验可以介绍一下吗？ @xiaoxinpro

**Comment by xiaoxinpro** [comment]
RAID 1确实可以提高数据安全，不过在我看来这样牺牲写入速度和存储容量是不值得的。另外如果是备份用那么数据本身就是冗余的，没有必要再做二次冗余。如果是共享存储服务器考虑数据安全可以使用异地容灾备份，可以有效防止地震、海啸、雷击等因素造成的数据丢失。

**Comment by yuhr123** [comment]
@xiaoxinpro 我采纳你的提议，在配置数据盘的部分，我会补充非阵列存储相关的内容。最终是否使用 RAID，让用户根据数据安全的敏感程度自行选择。
