### ISSUE TITLE
通过terminal安装grub到U盘后 启动需修改dev/sd的问题

### ISSUE THREAD

**Issue by sosmygirl** [getnas/getnas#6]
安装盘 /dev/sda
系统盘 /dev/sdb
grub 安装在 /dev/sdb上。
但启动显示需要从sda1上启动。但安装u盘已经u盘已经拔掉到了。
可以通过零时e修改成/dev/sdb1来启动系统。。
我不会永久办法方法。。
而图形安装没有问题

**Comment by yuhr123** [comment]
这个问题就很有灵性了 🤔

**Comment by sosmygirl** [comment]
已解决
