### ISSUE TITLE
建议挂载硬盘使用UUID方式

### ISSUE THREAD

**Issue by IdealDreamLast** [getnas/getnas#7]
感谢大神的分享！
最近在参考你的nas搭建方案，在方案三 直接使用 RAID 磁盘阵列 中，因为开机后分区设备名变化，会导致异常，建议统一使用UUID方式自动挂载分区

**Comment by yuhr123** [comment]
感谢提示，我前面也碰到了相关的问题，用 UUID 可能不是最佳方案，应该使用 PARTUUID。
有兴趣可以参考这篇 FAQ：https://github.com/getnas/getnas/blob/master/questions/uefi-cannot-boot.md

**Comment by 1a57danc3** [comment]
openmediavault 掛載方式是使用 `/srv/dev-disk-by-id-ata-{deviceVendor}_{deviceModel}_{serialNumber}-part{number}` 的格式
